# Generated by Django 4.2.29 on 2026-03-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'otp'], name='accounts_ot_user_id_1231dd_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['created_at'], name='accounts_ot_created_3fc6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='accounts_ta_status_7456d2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='accounts_ta_assigne_37cf4f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by'], name='accounts_ta_created_f6c172_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='accounts_ta_assigne_3b4b00_idx'),
        ),
    ]
