# Generated by Django 4.2.29 on 2026-03-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_auditlog_options_auditlog_action_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_user_id_2e9d8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_timesta_276167_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_user_id_d4cccd_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
