# Generated by Django 4.2.29 on 2026-04-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='field_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
